insert into public.vocabulary (
  id,
  kana,
  japanese,
  romaji,
  meaning_es,
  meaning_en,
  image_path,
  category,
  kana_series,
  source,
  approved
) values
  ('official-a-akachan', 'あ', 'あかちゃん', array['akachan']::text[], 'bebé', 'baby', 'akachan.webp', 'hiragana', 'あ', 'official', true),
  ('official-i-ichigo', 'い', 'いちご', array['ichigo']::text[], 'fresa', 'strawberry', 'ichigo.webp', 'hiragana', 'い', 'official', true),
  ('official-u-udon', 'う', 'うどん', array['udon']::text[], 'udon', 'udon noodles', 'udon.webp', 'hiragana', 'う', 'official', true),
  ('official-e-eiga', 'え', 'えいが', array['eiga']::text[], 'película', 'movie', 'eiga.webp', 'hiragana', 'え', 'official', true),
  ('official-o-onpu', 'お', 'おんぷ', array['onpu']::text[], 'nota musical', 'musical note', 'onpu.webp', 'hiragana', 'お', 'official', true),
  ('official-ka-kaeru', 'か', 'かえる', array['kaeru']::text[], 'rana', 'frog', 'kaeru.webp', 'hiragana', 'か', 'official', true),
  ('official-ki-kitsune', 'き', 'きつね', array['kitsune']::text[], 'zorro', 'fox', 'kitsune.webp', 'hiragana', 'き', 'official', true),
  ('official-ku-kuruma', 'く', 'くるま', array['kuruma']::text[], 'coche', 'car', 'kuruma.webp', 'hiragana', 'く', 'official', true),
  ('official-ke-keisanki', 'け', 'けいさんき', array['keisanki']::text[], 'calculadora', 'calculator', 'keisanki.webp', 'hiragana', 'け', 'official', true),
  ('official-ko-kodomo', 'こ', 'こども', array['kodomo']::text[], 'niño', 'child', 'kodomo.webp', 'hiragana', 'こ', 'official', true),
  ('official-sa-sakana', 'さ', 'さかな', array['sakana']::text[], 'pez', 'fish', 'sakana.webp', 'hiragana', 'さ', 'official', true),
  ('official-shi-shishiodoshi', 'し', 'ししおどし', array['shishiodoshi']::text[], 'fuente de bambú japonesa', 'bamboo fountain', 'shishiodoshi.webp', 'hiragana', 'し', 'official', true),
  ('official-su-suika', 'す', 'すいか', array['suika']::text[], 'sandía', 'watermelon', 'suika.webp', 'hiragana', 'す', 'official', true),
  ('official-se-senpuuki', 'せ', 'せんぷうき', array['senpuuki']::text[], 'ventilador', 'fan', 'senpuuki.webp', 'hiragana', 'せ', 'official', true),
  ('official-so-souji', 'そ', 'そうじ', array['souji']::text[], 'limpieza', 'cleaning', 'souji.webp', 'hiragana', 'そ', 'official', true),
  ('official-ta-tanuki', 'た', 'たぬき', array['tanuki']::text[], 'tanuki', 'tanuki', 'tanuki.webp', 'hiragana', 'た', 'official', true),
  ('official-chi-chikyuu', 'ち', 'ちきゅう', array['chikyuu']::text[], 'Tierra', 'Earth', 'chikyuu.webp', 'hiragana', 'ち', 'official', true),
  ('official-tsu-tsukue', 'つ', 'つくえ', array['tsukue']::text[], 'escritorio', 'desk', 'tsukue.webp', 'hiragana', 'つ', 'official', true),
  ('official-te-tegami', 'て', 'てがみ', array['tegami']::text[], 'carta', 'letter', 'tegami.webp', 'hiragana', 'て', 'official', true),
  ('official-to-toufu', 'と', 'とうふ', array['toufu']::text[], 'tofu', 'tofu', 'toufu.webp', 'hiragana', 'と', 'official', true),
  ('official-na-namida', 'な', 'なみだ', array['namida']::text[], 'lágrima', 'tear', 'namida.webp', 'hiragana', 'な', 'official', true),
  ('official-ni-ninjin', 'に', 'にんじん', array['ninjin']::text[], 'zanahoria', 'carrot', 'ninjin.webp', 'hiragana', 'に', 'official', true),
  ('official-nu-nurie', 'ぬ', 'ぬりえ', array['nurie']::text[], 'dibujo para colorear / libro para colorear', 'coloring page / coloring book', 'nurie.webp', 'hiragana', 'ぬ', 'official', true),
  ('official-ne-nendo', 'ね', 'ねんど', array['nendo']::text[], 'arcilla', 'clay', 'nendo.webp', 'hiragana', 'ね', 'official', true),
  ('official-no-norimaki', 'の', 'のりまき', array['norimaki']::text[], 'sushi enrollado', 'sushi roll', 'norimaki.webp', 'hiragana', 'の', 'official', true),
  ('official-ha-hanabi', 'は', 'はなび', array['hanabi']::text[], 'fuegos artificiales', 'fireworks', 'hanabi.webp', 'hiragana', 'は', 'official', true),
  ('official-hi-hitsuji', 'ひ', 'ひつじ', array['hitsuji']::text[], 'oveja', 'sheep', 'hitsuji.webp', 'hiragana', 'ひ', 'official', true),
  ('official-fu-fuuton', 'ふ', 'ふうとん', array['fuuton']::text[], 'futón', 'futon', 'fuuton.webp', 'hiragana', 'ふ', 'official', true),
  ('official-he-hebi', 'へ', 'へび', array['hebi']::text[], 'serpiente', 'snake', 'hebi.webp', 'hiragana', 'へ', 'official', true),
  ('official-ho-hotaru', 'ほ', 'ほたる', array['hotaru']::text[], 'luciérnaga', 'firefly', 'hotaru.webp', 'hiragana', 'ほ', 'official', true),
  ('official-ma-makura', 'ま', 'まくら', array['makura']::text[], 'almohada', 'pillow', 'makura.webp', 'hiragana', 'ま', 'official', true),
  ('official-mi-mikan', 'み', 'みかん', array['mikan']::text[], 'mandarina', 'mandarin orange', 'mikan.webp', 'hiragana', 'み', 'official', true),
  ('official-mu-mushiba', 'む', 'むしば', array['mushiba']::text[], 'caries', 'cavity', 'mushiba.webp', 'hiragana', 'む', 'official', true),
  ('official-me-megane', 'め', 'めがね', array['megane']::text[], 'gafas', 'glasses', 'megane.webp', 'hiragana', 'め', 'official', true),
  ('official-mo-momiji', 'も', 'もみじ', array['momiji']::text[], 'hojas rojas de otoño', 'autumn leaves', 'momiji.webp', 'hiragana', 'も', 'official', true),
  ('official-ya-yasai', 'や', 'やさい', array['yasai']::text[], 'verduras', 'vegetables', 'yasai.webp', 'hiragana', 'や', 'official', true),
  ('official-yu-yuuhi', 'ゆ', 'ゆうひ', array['yuuhi']::text[], 'atardecer', 'sunset', 'yuuhi.webp', 'hiragana', 'ゆ', 'official', true),
  ('official-yo-youchien', 'よ', 'ようちえん', array['youchien']::text[], 'guardería', 'kindergarten', 'youchien.webp', 'hiragana', 'よ', 'official', true),
  ('official-ra-rakuda', 'ら', 'らくだ', array['rakuda']::text[], 'camello', 'camel', 'rakuda.webp', 'hiragana', 'ら', 'official', true),
  ('official-ri-ringo', 'り', 'りんご', array['ringo']::text[], 'manzana', 'apple', 'ringo.webp', 'hiragana', 'り', 'official', true),
  ('official-ru-iruka', 'る', 'いるか', array['iruka']::text[], 'delfín', 'dolphin', 'iruka.webp', 'hiragana', 'る', 'official', true),
  ('official-re-reizouko', 'れ', 'れいぞうこ', array['reizouko']::text[], 'frigorífico', 'refrigerator', 'reizouko.webp', 'hiragana', 'れ', 'official', true),
  ('official-ro-rousoku', 'ろ', 'ろうそく', array['rousoku']::text[], 'vela', 'candle', 'rousoku.webp', 'hiragana', 'ろ', 'official', true),
  ('official-yu-yuki', 'ゆ', 'ゆき', array['yuki']::text[], 'nieve', 'snow', 'yuki.webp', 'hiragana', 'ゆ', 'official', true),
  ('official-wa-wataame', 'わ', 'わたあめ', array['wataame']::text[], 'algodón de azúcar', 'cotton candy', 'wataame.webp', 'hiragana', 'わ', 'official', true),
  ('official-n-otsukaresan', 'ん', 'おつかれさん', array['otsukaresan']::text[], 'buen trabajo', 'good job', 'otsukaresan.webp', 'hiragana', 'ん', 'official', true)
on conflict (id) do update set
  kana = excluded.kana,
  japanese = excluded.japanese,
  romaji = excluded.romaji,
  meaning_es = excluded.meaning_es,
  meaning_en = excluded.meaning_en,
  image_path = excluded.image_path,
  category = excluded.category,
  kana_series = excluded.kana_series,
  source = excluded.source,
  approved = excluded.approved;
